<?php $defaultFontSize = $helper->getConfig('font_size', 'checkout') == '' ? 0 : $helper->getConfig('font_size', 'checkout'); ?>
<html>
<head>
    <link href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/css/TIG/MyParcel2014/myparcel_options.css?v=2'; ?>" rel="stylesheet" type="text/css">
    <script>
        var BASE_URL = '<?php echo Mage::getUrl('',array('_secure'=>true));?>';
        var defaultFontSize = <?php echo $defaultFontSize;?>;
    </script>
    <style>
        body {
            margin: 0;
            word-wrap: break-word;
            overflow: hidden;
        }
    </style>

    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/js/TIG/MyParcel2014/jquery.min.js?v=2'; ?>"></script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/js/TIG/MyParcel2014/moment.min.js?v=2'; ?>"></script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/js/TIG/MyParcel2014/iframe_checkout.js?v=2'; ?>"></script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/js/TIG/MyParcel2014/myparcel.js?v=2'; ?>"></script>
    <script>
        setTimeout(function () {
            new MyParcel();
            window.mypa.fn.load();

            var fonts = parent.mypajQuery('label').css('font-family');
            var fontSize;
            if (defaultFontSize < 9) {
                fontSize = parent.mypajQuery('label').css('font-size');
            } else {
                fontSize = defaultFontSize;
            }

            $('#mypa-delivery-options-container').css("font-family", fonts).css("font-size", fontSize);
        }, 500);
    </script>
</head>
<body>
    <div id="myparcel-template">

        <?php require(Mage::getBaseDir('app') . DS . 'design/frontend/base/default/template/TIG/MyParcel2014/checkout/mypa_custom_css.php'); ?>

        <div id='mypa-delivery-options-container'>
            <div class="mypa-overlay">
                <span id="mypa-no-options">Adres ophalen...</span>
            </div>
            <div id="mypa-slider">
                <!-- First frame -->
                <div id="mypa-delivery-type-selection" class="mypa-tab-container mypa-slider-pos-0">
                    <div id="mypa-slider-holder">
                        <div id="mypa-date-slider-left"
                             class="mypa-arrow-left mypa-back-arrow mypa-date-slider-button mypa-slider-disabled"></div>
                        <div id="mypa-date-slider-right"
                             class="mypa-arrow-right myapa-next-arrow mypa-date-slider-button mypa-slider-disabled"></div>
                        <div id="mypa-tabs-container">
                            <div id='mypa-tabs'>
                            </div>
                        </div>
                    </div>
                    <div class='mypa-delivery-content mypa-container-lg'>
                        <div class='mypa-header-lg mypa-delivery-header'>
                            <span class="mypa-header-title"><b>BEZORGOPTIES:</b></span> <span class="mypa-location"></span>
                        </div>
                        <div id='mypa-delivery-body'>
                            <div id='mypa-delivery-row' class='mypa-row-lg'>
                                <input id='mypa-delivery-option-check' type="radio" name="mypa-delivery-type"
                                       checked>
                                <label id='mypa-delivery-options-title' class='mypa-row-title'
                                       for="mypa-delivery-option-check">
                                    <div class="mypa-checkmark mypa-main">
                                        <div class="mypa-circle mypa-circle-checked"></div>
                                        <div class="mypa-checkmark-stem"></div>
                                        <div class="mypa-checkmark-kick"></div>
                                    </div>
                                    <span
                                            class="mypa-highlight"><?php echo $helper->getConfig('delivery_title', 'delivery'); ?></span>
                                    <span id="mypa-global_delivery_price" class='mypa-price' style="display:none"></span>
                                </label>
                                <div id='mypa-delivery-options' class='mypa-content-lg'>
                                </div>
                            </div>
                            <?php if ($packageType == 2): ?>
                                <div id='mypa-mailbox-row' class='mypa-row-lg' style="display:none">
                                    <input type="radio" name="mypa-delivery-type" id="mypa-mailbox-location">
                                    <label id='mypa-mailbox-options-title' class='mypa-row-title'
                                           for="mypa-mailbox-location">
                                        <div class="mypa-checkmark mypa-main">
                                            <div class="mypa-circle"></div>
                                            <div class="mypa-checkmark-stem"></div>
                                            <div class="mypa-checkmark-kick"></div>
                                        </div>
                                        <span class='mypa-price mypa-mailbox-price'>
                                            <?php echo $mailBoxPrice; ?>
                                        </span>
                                        <span class="mypa-highlight">
                                            <?php echo $helper->getConfig('mailbox_title', 'mailbox'); ?>
                                        </span>
                                    </label>
                                </div>
                            <?php endif;?>
                            <div id='mypa-pickup-row' class='mypa-row-lg'>
                                <input type="radio" name="mypa-delivery-type" id="mypa-pickup-location">
                                <label id='mypa-pickup-options-title' class='mypa-row-title'
                                       for="mypa-pickup-location">
                                    <div class="mypa-checkmark mypa-main">
                                        <div class="mypa-circle"></div>
                                        <div class="mypa-checkmark-stem"></div>
                                        <div class="mypa-checkmark-kick"></div>
                                    </div>
                                    <span
                                            class="mypa-highlight"><?php echo $helper->getConfig('pickup_title', 'pickup'); ?></span>
                                    <span id="mypa-global_pickup_price" class='mypa-price' style="display:none"></span>
                                </label>
                                <div id='mypa-pickup-options-content' class='mypa-content-lg'>
                                    <div>
                                        <label for='mypa-pickup' class='mypa-row-subitem mypa-pickup-selector'>
                                            <input id='mypa-pickup' type="radio" name="mypa-delivery-time">
                                            <label for="mypa-pickup" class="mypa-checkmark">
                                                <div class="mypa-circle"></div>
                                                <div class="mypa-checkmark-stem"></div>
                                                <div class="mypa-checkmark-kick"></div>
                                            </label>
                                            <span class='mypa-price mypa-pickup-price'></span>
                                            <span class="mypa-highlight">Vanaf 16.00 uur</span><span
                                                    class='mypa-address' id="mypa-pickup-address"></span>
                                        </label>
                                        <label for='mypa-pickup-express'
                                               class='mypa-row-subitem mypa-pickup-selector'>
                                            <input id='mypa-pickup-express' type="radio" name="mypa-delivery-time">
                                            <label for='mypa-pickup-express' class="mypa-checkmark">
                                                <div class="mypa-circle mypa-circle-checked"></div>
                                                <div class="mypa-checkmark-stem"></div>
                                                <div class="mypa-checkmark-kick"></div>
                                            </label>
                                            <span class='mypa-price mypa-pickup-express-price'></span>
                                            <span class="mypa-highlight">Vanaf 8.30 uur</span><span
                                                    class='mypa-address' id="mypa-pickup-express-address"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="mypa-location-selector" class="mypa-tab-container mypa-slider-pos-0">
                    <!-- Second frame -->
                    <div id='mypa-tabs-2'>
                    </div>
                    <div class='mypa-container-lg mypa-delivery-content'>
                        <div class='mypa-header-lg mypa-delivery-header'>
                                    <span id='mypa-back-arrow'><b>AFHALEN </b><span
                                                class="mypa-location-time"></span></span>
                        </div>
                        <div id="mypa-location-container">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>