<div id="mp_checkout" class="mp_checkout">

    <div class="mp_checkout-container">
        <div class="mp_checkout-content">
            <ul class="mp-bar">
                <li>
                    <div class="mp-day-holder">
                        <span class="mp-day-title">di</span>
                        <span class="mp-day-date">22-3</span>
                    </div>
                </li>
                <li class="mp-active">
                    <div class="mp-day-holder">
                        <span class="mp-day-title">wo</span>
                        <span class="mp-day-date">23-3</span>
                    </div>
                </li>
                <li>
                    <div class="mp-day-holder">
                        <span class="mp-day-title">do</span>
                        <span class="mp-day-date">24-3</span>
                    </div>
                </li>
                <li>
                    <div class="mp-day-holder">
                        <span class="mp-day-title">vr</span>
                        <span class="mp-day-date">25-3</span>
                    </div>
                </li>
            </ul>

            <div class="mp-methods">
                <div class="mp-methods-delivery">
                    <ul>
                        <li>
                            <div class="mp-method-item">
                                <div class="mp-radio"></div>
                                <div class="mp-method-title"><span class="mp-method-title-moment">Ochtend</span> <span class="mp-method-title-price">+ €10,-</span></div>
                                <div class="mp-method-time">10.00 - 12.00 uur</div>
                            </div>
                        </li>
                        <li>
                            <div class="mp-method-item">
                                <div class="mp-radio"></div>
                                <div class="mp-method-title"><span class="mp-method-title-moment">Standaard</span></div>
                                <div class="mp-method-time">12.00 - 16.00 uur</div>
                            </div>
                            <div class="mp-method-options">
                                <ul>
                                    <li>
                                        <div class="mp-radio-small"></div>
                                        <div class="mp-method-option-title-holder">
                                            <span class="mp-method-option-title">Handtekening voor ontvangst <span class="mp-method-title-price">+ €2,-</span></span>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="mp-radio-small"></div>
                                        <div class="mp-method-option-title-holder">
                                            <span class="mp-method-option-title">Niet bij de buren aanbieden </span> <span class="mp-method-title-price">+ €2,-</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <div class="mp-method-item">
                                <div class="mp-radio mp-active"></div>
                                <div class="mp-method-title"><span class="mp-method-title-moment">Avond</span> <span class="mp-method-title-price">+ €1,25,-</span></div>
                                <div class="mp-method-time">18.00 - 21.30 uur</div>
                            </div>
                        </li>
                        <li>
                            <div class="mp-method-item">
                                <div class="mp-radio mp-radio-open"></div>
                                <div class="mp-method-title"><span class="mp-method-title-moment">Ophalen bij een PostNL locatie</span></div>
                                <div class="mp-method-time">10.00 - 12.00 uur</div>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>

        </div>

    </div>
</div>