// Generated by CoffeeScript 1.10.0
(function() {
    var CARRIER, MORNING_PICKUP, NATIONAL, NORMAL_PICKUP, PICKUP_TIMES, displayOtherTab, fetchDeliveryOptions, initialize, makeSlider, obj, orderDays, preparePickup, renderDays, renderExpressPickup, renderPage, renderPickup, renderPickupLocation, slideLeft, slideRight;

    window.mypa = {
        fn: {},
        settings: {}
    };

    NATIONAL = 'NL';

    CARRIER = 1;

    MORNING_PICKUP = '08:30:00';

    NORMAL_PICKUP = '16:00:00';

    PICKUP_TIMES = (
        obj = {},
            obj["" + MORNING_PICKUP] = 'morning',
            obj["" + NORMAL_PICKUP] = 'normal',
            obj
    );

    displayOtherTab = function() {
        return jQuery('.mypa-tab-container').toggleClass('mypa-slider-pos-1').toggleClass('mypa-slider-pos-0');
    };

    window.mypa.fn.updatePage = function() {
        return fetchDeliveryOptions();
    };

    fetchDeliveryOptions = function(postal_code, number, street) {
        var options, settings, urlBase;
        settings = window.mypa.settings;
        //urlBase = "api/delivery_options";
        urlBase = "https://api.myparcel.nl/delivery_options";


        if (number == null) {
            number = settings.number;
        }
        if (number == null) {
            number = 100;
        }
        if (postal_code == null) {
            postal_code = settings.postal_code;
        }
        if (postal_code == null) {
            postal_code = "1442CE";
        }
        if (street == null) {
            street = settings.street;
        }
        jQuery('.mypa-location').html("" + street);
        options = {
            url: urlBase,
            data: {
                cc: NATIONAL,
                carrier: CARRIER,
                number: number,
                postal_code: postal_code,
                delivery_time: settings.delivery_time != null ? settings.delivery_time : void 0,
                delivery_date: settings.delivery_date != null ? settings.delivery_date : void 0,
                cutoff_time: settings.cutoff_time != null ? settings.cutoff_time : void 0,
                dropoff_days: settings.dropoff_days != null ? settings.dropoff_days : void 0,
                dropoff_delay: settings.dropoff_delay != null ? settings.dropoff_delay : void 0,
                deliverydays_window: settings.deliverydays_window != null ? settings.deliverydays_window : void 0,
                exlude_delivery_type: settings.exclude_delivery_type != null ? settings.exclude_delivery_type : void 0
            },
            success: renderPage,
            error: function (xhr, status) {
                console.log(xhr);
                console.log(status);
            }
        };
        return jQuery.ajax(options);
    };


    /*
     * Starts the render of the delivery options with the preset config
     */

    renderPage = function(response) {
        renderDays(response.data.delivery);
        return preparePickup(response.data.pickup);
    };

    preparePickup = function(pickupOptions) {
        var filter, i, j, len, len1, name, pickupLocation, ref, time;
        window.mypa.pickupFiltered = filter = {};
        for (i = 0, len = pickupOptions.length; i < len; i++) {
            pickupLocation = pickupOptions[i];
            ref = pickupLocation.time;
            for (j = 0, len1 = ref.length; j < len1; j++) {
                time = ref[j];
                if (filter[name = PICKUP_TIMES[time.start]] == null) {
                    filter[name] = [];
                }
                filter[PICKUP_TIMES[time.start]].push(pickupLocation);
            }
        }
        if (filter[PICKUP_TIMES[MORNING_PICKUP]] == null) {
            jQuery('#mypa-pickup-express').parent().css({
                display: 'none'
            });
        }
        jQuery('label[for=mypa-pickup]').off().bind('click', renderPickup);
        return jQuery('label[for=mypa-pickup-express]').off().bind('click', renderExpressPickup);
    };

    renderPickup = function() {
        renderPickupLocation(window.mypa.pickupFiltered[PICKUP_TIMES[NORMAL_PICKUP]]);
        jQuery('#mypa-pickup').prop('checked', true);
        return false;
    };

    renderExpressPickup = function() {
        renderPickupLocation(window.mypa.pickupFiltered[PICKUP_TIMES[MORNING_PICKUP]]);
        jQuery('#mypa-pickup-express').prop('checked', true);
        return false;
    };

    renderPickupLocation = function(data) {
        var html, index, location, results;
        displayOtherTab();
        jQuery('#mypa-location-container').html('');
        results = [];
        for (index in data) {
            location = data[index];
            console.log(location);
            html = "<div for='mypa-pickup-location-" + index + "' class=\"mypa-row-lg\">\n  <input id=\"mypa-pickup-location-" + index + "\" type=\"radio\" name=\"mypa-pickup-option\">\n  <label for='mypa-pickup-location-" + index + "' class='mypa-row-title'>\n    <div class=\"mypa-checkmark mypa-main\">\n      <div class=\"mypa-circle\"></div>\n      <div class=\"mypa-checkmark-stem\"></div>\n      <div class=\"mypa-checkmark-kick\"></div>\n    </div>\n    <span class=\"mypa-highlight\">" + location.location + ", <b>" + location.street + " " + location.number + "</b>,\n    <i>" + (String(Math.round(location.distance / 100) / 10).replace('.', ',')) + " Km</i></span>\n  </label>\n</div>";
            results.push(jQuery('#mypa-location-container').append(html));
        }
        return results;
    };


    /*
     * Renders the available days for delivery
     */

    renderDays = function(deliveryDays) {
        var $el, date, delivery, html, index;
        deliveryDays.sort(orderDays);
        $el = jQuery('#mypa-tabs').html('');
        jQuery('#mypa-delivery-options-container').width();
        for (index in deliveryDays) {
            delivery = deliveryDays[index];
            date = moment(delivery.date);
            html = "<input type=\"radio\" id=\"mypa-date-" + index + "\" class=\"mypa-date\" name=\"date\" checked>\n<label for='mypa-date-" + index + "' class='mypa-tab active'>\n  <span class='day-of-the-week'>" + (date.format('dddd')) + "</span>\n  <br>\n  <span class='date'>" + (date.format('DD MMMM')) + "</span>\n</label>";
            $el.append(html);
        }
        $el.width(deliveryDays.length * 105);
        return makeSlider();
    };


    /*
     * Initializes the slider
     */

    makeSlider = function() {
        var slider;
        slider = window.mypa.slider = {};
        slider.barLength = jQuery('#mypa-tabs-container').outerWidth();
        slider.bars = jQuery('#mypa-tabs').outerWidth() / slider.barLength;
        slider.currentBar = 1;
        jQuery('#mypa-date-slider-right').removeClass('mypa-slider-disabled');
        jQuery('#mypa-date-slider-left').off().bind('click', slideLeft);
        return jQuery('#mypa-date-slider-right').off().bind('click', slideRight);
    };


    /*
     * Event handler for sliding the date slider to the left
     */

    slideLeft = function(e) {
        var $el, left, slider;
        slider = window.mypa.slider;
        if (slider.currentBar === 1) {
            jQuery(e.currentTarget).addClass('mypa-slider-disabled');
        } else if (slider.currentBar < 1) {
            return;
        } else {
            jQuery(e.currentTarget).removeClass('mypa-slider-disabled');
        }
        jQuery('#mypa-date-slider-right').removeClass('mypa-slider-disabled');
        slider.currentBar--;
        $el = jQuery('#mypa-tabs');
        left = slider.currentBar * slider.barLength * -1;
        left = parseInt(left / 104.0) * 104;
        console.log(left);
        return $el.css({
            left: left
        });
    };


    /*
     * Event handler for sliding the date slider to the right
     */

    slideRight = function(e) {
        var $el, left, slider;
        slider = window.mypa.slider;
        if (parseInt(slider.currentBar) === parseInt(slider.bars - 1)) {
            jQuery(e.currentTarget).addClass('mypa-slider-disabled');
        } else if (slider.currentBar >= slider.bars - 1) {
            return;
        } else {
            jQuery(e.currentTarget).removeClass('mypa-slider-disabled');
        }
        jQuery('#mypa-date-slider-left').removeClass('mypa-slider-disabled');
        slider.currentBar++;
        $el = jQuery('#mypa-tabs');
        left = slider.currentBar * slider.barLength * -1;
        console.log('------------');
        console.log(left);
        left = parseInt(left / 104.0) * 104;
        console.log(left);
        return $el.css({
            left: left
        });
    };


    /*
     * Order function for the delivery array
     */

    orderDays = function(dayA, dayB) {
        var dateA, dateB, max;
        dateA = moment(dayA.date);
        dateB = moment(dayB.date);
        max = moment.max(dateA, dateB);
        if (max === dateA) {
            return 1;
        }
        return -1;
    };

    initialize = function() {
        moment.locale(NATIONAL);
        fetchDeliveryOptions();
        jQuery('#mypa-back-arrow').bind('click', displayOtherTab);
        return null;
    };

    jQuery(document).ready(initialize);

}).call(this);

//# sourceMappingURL=myparcel.js.map
